version: '3.4'

services:
  poplavok-site:
    image: poplavok-site
    build:
      context: .
      dockerfile: ./site.Dockerfile
    volumes:
    - .:/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 site/manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - pyro-ns
      - pyro-server
  pyro-server: 
    image: pyro-server
    build: 
      context: .
      dockerfile: ./pyro-server.Dockerfile
    volumes:
    - .:/app
    ports:
      - 52603:52603
    command: ["python3", "runPyroServer.py"]
    depends_on:
      - pyro-ns
  pyro-ns:
      image: farshidtz/pyro4-ns
      privileged: true
      restart: always
      ports:
        - 9090:9090
      command: ["--host=pyro-ns","--nathost=localhost","--natport=9090"]