version: '3.4'

services:
  poplavokalgorithm:
    image: poplavokalgorithm
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - pyro-ns
  pyro-ns:
      image: farshidtz/pyro4-ns
      privileged: true
      restart: always
      ports:
        - 9090:9090
      command: ["--host=pyro-ns","--nathost=localhost","--natport=9090"]
