version: '3.4'

services:
  poplavokalgorithm:
    image: poplavokalgorithm
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 site/manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - pyro-ns
  pyro-ns:
      image: farshidtz/pyro4-ns
      privileged: true
      restart: always
      ports:
        - 9090:9090
      command: ["--host=pyro-ns","--nathost=localhost","--natport=9090"]